/* App component */
export const SET_ROUTE = 'SET_ROUTE';
export const SET_LOCATION = 'SET_LOCATION';
export const REQUEST_CURRENT_POSITION_PENDING = 'REQUEST_CURRENT_POSITION_PENDING';
export const REQUEST_CURRENT_POSITION_SUCCESS = 'REQUEST_CURRENT_POSITION_SUCCESS';
export const REQUEST_CURRENT_POSITION_FAILED = 'REQUEST_CURRENT_POSITION_FAILED';

/* SearchField component */
export const UPDATE_INPUT = 'UPDATE_INPUT;'
export const REQUEST_SEARCH_OPTIONS_PENDING = 'REQUEST_SEARCH_OPTIONS_PENDING';
export const REQUEST_SEARCH_OPTIONS_SUCCESS = 'REQUEST_SEARCH_OPTIONS_SUCCESS';
export const REQUEST_SEARCH_OPTIONS_FAILED = 'REQUEST_SEARCH_OPTIONS_FAILED';